# Generated by Django 4.1.3 on 2022-11-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nombre',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
