# Generated by Django 4.1.3 on 2022-11-27 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'prioridad',
                'verbose_name_plural': 'prioridades',
                'db_table': 'prioridad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('abono', models.FloatField(blank=True, default=0, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('precio', models.FloatField(blank=True, default=0, null=True)),
                ('retribucion', models.BooleanField(blank=True, null=True)),
                ('culminado', models.BooleanField(default=True)),
                ('fechaHecho', models.DateTimeField(blank=True, null=True)),
                ('fechaProceso', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ManyToManyField(blank=True, null=True, to='colaboradores.colaborador')),
                ('kanban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.kanban')),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWeb.prioridad')),
                ('producto', models.ManyToManyField(blank=True, null=True, to='productos.producto')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'db_table': 'tarea',
                'ordering': ['id'],
            },
        ),
    ]
